dist: xenial

language: php

php:
    - '7.2'
    - '7.3'
    - '7.4snapshot'

script:
    # run phar
    - php rector --debug
    - php rector.phar --debug

    # standalone
    - mkdir standalone
    - cd standalone
    # maybe sleep here?
    - composer require rector/rector-prefixed:@dev --dev
    - vendor/bin/rector

    # @todo when the above one pass, try to install it alongside symfony/console 3.2, then symfony/console 2.8, turn into 4 jobs

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache
