dist: xenial

language: php

php:
    - '7.2'
    - '7.3'
    - '7.4snapshot'

# runs phpunit by default
script: skip

jobs:
    include:
        -
            stage: Run PHAR
            script:
                - php rector
                - php rector.phar

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache
