dist: xenial

language: php

php:
    - '7.2'
    - '7.3'
    - '7.4snapshot'


# would run phpunit instead
script: skip

jobs:
    include:
        -
            stage: test
            name: "Run PHARs"
            script:
                - php rector --debug
                - php rector.phar --debug
                - rector --debug
                - rector.phar --debug

        -
            stage: test
            name: "Run as Composer Dependency"
            before_script:
                - mkdir standalone
                - cd standalone
                # wait for deploy to packagist
                - sleep 30
            script:
                - composer require rector/rector-prefixed:@dev --dev
                - vendor/bin/rector --debug

        -
            stage: test
            name: "Install with Symfony 2.8"
            before_script:
                - mkdir standalone
                - cd standalone
                # wait for deploy to packagist
                - sleep 30
            script:
                - composer require symfony/console:3.4
                - composer require rector/rector-prefixed:@dev --dev
                - vendor/bin/rector --debug

        -
            stage: test
            name: "Install with Symfony 3.4"
            before_script:
                - mkdir standalone
                - cd standalone
                # wait for deploy to packagist
                - sleep 30
            script:
                - composer require symfony/console:3.4
                - composer require rector/rector-prefixed:@dev --dev
                - vendor/bin/rector --debug

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
