dist: xenial

language: php

php:
    - '7.2'
    - '7.3'
    - '7.4snapshot'

script:
    # run phar
    - php rector
    - php rector.phar

    # standalone
    - composer require rector/rector-prefixed:@dev --dev
    - vendor/bin/rector

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache
