name: Run PHAR with Set

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    run_phar_with_set:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: |
                    php rector process fixture/SomeFileWithDeadCode.php --set dead-code --dry-run
