name: With Sets

on: [pull_request, push]

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        config: "rector-dead-code"
                        dry_run_optoin: "--dry-run"

                    -
                        config: "rector-nette-utils-code-quality"
                        dry_run_optoin: ""

        name: Set ${{ matrix.actions.set }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: php rector process fixture --config ${{ matrix.actions.config }} ${{ matrix.actions.dry_run_option }} --ansi
